name: documentation

on:
  push:
    branches:
      - master
      - feature/**

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install packages
        run: |
          sudo gem install asciidoctor asciidoctor-pdf rouge

      - name: Setup Boost
        run: |
          REF=${GITHUB_BASE_REF:-$GITHUB_REF}
          cd ..
          git clone --depth 1 https://github.com/boostorg/boost.git boost-root
          cd boost-root
          cp -r $GITHUB_WORKSPACE/* libs/qvm
          git submodule update --init tools/build
          git submodule update --init libs/config
          ./bootstrap.sh

      - name: Create user-config.jam
        run: |
          echo "using asciidoctor ;" > ~/user-config.jam

      - name: Build documentation
        run: |
          cd ../boost-root/libs/qvm/doc
          ../../../b2

      - name: Generate headers
        run: |
          cd ../boost-root/libs/$LIBRARY
          python3 gen/generate_single_header.py -i include/boost/qvm/all.hpp -p include -o doc/html/qvm.hpp boost/qvm
          python3 gen/generate_single_header.py -i include/boost/qvm/lite.hpp -p include -o doc/html/qvm_lite.hpp boost/qvm

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: ../boost-root/libs/qvm/doc/html
